((haskell-mode . ((haskell-indent-spaces . 4)
                  (haskell-process-use-ghci . t)
                  (intero-project-root . "/home/inuits/iis")))
 (hamlet-mode . ((hamlet/basic-offset . 4)
                 (haskell-process-use-ghci . t))))
