NewsAdmin: News
NewsAdminIndex: News overview
NewsAdminNew: New news item
NewsAdminEdit: Edit news item
NoNewsFound: No news items found

Back: Back
Save: Save
Delete: Delete
Upload: Upload
Rename: Rename
Create: Create
Confirm: Confirm
Submit: Submit
Change: Change
Remove: Remove
BackHome: back to homepage
Deactivate: Deactivate
Activate: Activate

SuccessCreate: Successfully created
SuccessUpload: Successfully uploaded
SuccessReplace: Successfully replaced
SuccessUpdate: Successfully updated
SuccessDelete: Successfully deleted
SuccessRename: Successfully renamed
SuccessChgPwd: Successfully changed password
FailDelete: Failed to delete
FailRename: Failed to rename

LogNewsCreated name@Text: Created news item "#{name}"
LogNewsUpdated name@Text: Updated news item "#{name}"
LogNewsDeleted name@Text: Deleted news item "#{name}"
LogUserCreated name@Text: Created user "#{name}"
LogUserUpdated name@Text: Updated user "#{name}"
LogUserDeleted name@Text: Deleted user "#{name}"
LogUserChangedPassword name@Text: Changed password for user "#{name}"
LogUserRequestedPassword name@Text: Send a password reset token to user "#{name}"
LogUserDeactivated name@Text: Deactivated user "#{name}"
LogUserActivated name@Text: Activated user "#{name}"

Name: Name
FirstName: First name
LastName: Last name
FullName: Full name
BirthNumber: Birth number
Address: Address
City: City
PostalCode: Postal code
Email: Email
EmailAddress: E-mail address
Type: Type
Url: Url
Content: Content
Category: Category
CreatedOn: Created on
Order: Order
Label: Label
Description: Description
UploadedOn: Uploaded on
Username: Username
Password: Password
RetypePassword: Retype password
RememberMe: Remember Me
Register: Register
RegisterANewMembership: Register a new membership
ForgotMyPassword: I forgot my password
AlreadyHaveAMembership: I already have a membership
SignIn: Sign in
LogOut: Log out
ToggleNavigation: Toggle navigation
Supervisor: Supervisor
Repository: Repository

Dashboard: Dashboard
Administration: Administrace
NotLoggedIn: Not logged in
Logout: Logout

TimeJustNow: Just now
TimeSecondsAgo time@Text: #{time} seconds ago
TimeOneMinuteAgo: a minute ago
TimeMinutesAgo time@Text: #{time} minutes ago
TimeOneHourAgo: an hour ago
TimeAboutHoursAgo time@Text: about #{time} hours ago
TimeAt time@Text: at #{time}
TimeDaysAgo time@Text: #{time} days ago
TimeWeekAgo time@Text: #{time} week ago
TimeWeeksAgo time@Text: #{time} weeks ago
TimeOnYear time@Text: on #{time}
DayOfWeekFmt: %l:%M %p on %A

AccountSettings: Account settings
MenuUsers: Users
UserIndex: User overview
NewUser: New user
EditUser t@Text: t
DeletedUser t@Text: User "#{t}" deleted
NoUsersFound: No users found.
ChangeAccountSettings: Modify account settings
ChangeRoles: Select roles
ChangePassword: Change password
ResetPassword: Reset password
RequestResetTokenText: Reset this user's password and send him/her an email with a new verification token
RequestResetTokenButton: Request password reset
PasswordResetTokenSend: Password reset link send
PasswordTooShort: Password is too short
PasswordMismatch: Passwords don't match
Roles: Roles
UserDeactivated: User deactivated
UserActivated: User activated
UserStillPending: Can't perform action user is still pending
LastLogin: Last login
AccountStatus: Account status
AccountPending: Pending
AccountActive: Active
AccountInactive: Inactive
AccountAlreadyActivated: This account is already activated
ActivationSuccess: Account successfully activated
TokenMismatch: Invalid token

ActionLogIndex: Activities
NoActionLogsFound: No activities found
AllLogs: All activities
PersonalLogs: Your activities
InvalidOffset: Invalid value for "offset"
InvalidLimit: Invalid value for "limit"
LoadMore: load more